### ISSUE TITLE
Do I just need to update offsets ?

### ISSUE THREAD

**Issue by EXC3L-YT** [Kix48/R6Offline#4]
Does this just require the offsets updated ?
Or must I add other things to it
Also if I was to injector this online would it work but I would get a ban or would it just not woke at all ?

**Comment by Kix48** [comment]
You will need to update the offsets. However some things have changed directly and some features won’t work anymore. Also r6 has in game checks for some of these features but I’ll leave that up to your research. Finally, BE blocks all processes from having a handle for the protected process. Thus, this will not work with battleye.
